language: python

python:
  - "2.7"

sudo: required  # Required for docker
services:
  - docker
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-matplotlib  # For runbot badges

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE=runbot_skip_tests,runbot_build_instructions,runbot_travis2docker

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sed -i "s/\/dependencies\//\//g" ${HOME}/runbot-addons/.travis_requirements.sh
  - if [[ "${TESTS}" == "1"  ]]; then ${HOME}/runbot-addons/.travis_requirements.sh; fi

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
